### ISSUE TITLE
Made a huge comprehensive list of tooltip and buff icon errors over on Reddit

### ISSUE THREAD

**Issue by chickenwyr** [ValveSoftware/Dota2-Gameplay#2524]
### Hero and spell

almost all

### Description

Many many tooltips are missing key information or just straight up wrong. I made a huge long list compiling all I could find,. Linked here is the reddit post I made: 

https://www.reddit.com/r/DotA2/comments/x1ucct/massive_comprehensive_list_of_every_error/

**Comment by Aphotic** [comment]
do edit your post here to have all the reddit detail here as well! will be handy for devs ↨♥

**Comment by jaredeg** [comment]
Hoodwink's aghs decoy wont cast Sharpshooter if main hero doesn't have enough mana for sharpshooter

**Comment by Mabadman** [comment]
Additions:
Naga Siren's shard: #2551
Arc Warden's Flux: Debuff tooltip incorrectly (as of 7.32) states that the inflicted slow will cease once the debuff target is near a friendly unit
![image](https://user-images.githubusercontent.com/42493726/187734865-e8d02638-fe24-4af8-8d04-f3259c9d7f5f.png)

**Comment by Aphotic** [comment]
@chickenwyr 
https://old.reddit.com/r/DotA2/comments/x4imjq/dota_2_update_2_for_9222_9322_utc/
check & update both of your lists please, and check how many of the issues you reported are fixed. 👍🏻

**Comment by shaileshgarg** [comment]
Mars Scepter Bulwak Active Buff Tooltip for Soldiers say slow is 20%, but the slow should be 30%.

**Comment by dobacetr** [comment]
![image](https://user-images.githubusercontent.com/97127808/189098097-076f1495-2771-46bb-b1be-d2c3f539edf1.png)

### Wraith King
- skeleteon additional tooltip is displayed at the Mortal Strike, while the ability has been moved to Vampiric Spirit. It should either be moved to Vampiric Spirit or  Wraithfire Blast.

**Comment by nathank-valve** [comment]
Many of these issues have now been fixed. If you don't mind editing your post to convert these to Github Items ( add `- [ ] ` to the beginning of each bullet point), that will enable me to cross off the ones that were fixed

**Comment by chickenwyr** [comment]
> Many of these issues have now been fixed. If you don't mind editing your post to convert these to Github Items ( add `- [ ] ` to the beginning of each bullet point), that will enable me to cross off the ones that were fixed. Check out this post as an example: #561

I'll be happy to once I get back to my PC next week

**Comment by Stephanie55** [comment]
For pudge, the duration of E is not written.

**Comment by Aphotic** [comment]
> > Many of these issues have now been fixed. If you don't mind editing your post to convert these to Github Items ( add `- [ ] ` to the beginning of each bullet point), that will enable me to cross off the ones that were fixed. Check out this post as an example: #561
> 
> I'll be happy to once I get back to my PC next week

^reminder

**Comment by chickenwyr** [comment]
> 

Done!

**Comment by chickenwyr** [comment]
> Many of these issues have now been fixed. If you don't mind editing your post to convert these to Github Items ( add `- [ ] ` to the beginning of each bullet point), that will enable me to cross off the ones that were fixed. Check out this post as an example: #561

Done!

**Comment by nathank-valve** [comment]
Okay, the list should be updated now. I also fixed a few more that I missed last time - should ship soon. A couple notes:

Damage Type text isn't colored if the damage type can vary or is unknown. It's often unknown if the ability applies bonus damage, although it's true that bonus damage is typically applied to attacks as physical damage. A good example of the former is Elder Titan's Echo Stomp isn't red because the Spirit Form uses the same ability but deals magical damage instead.

Dazzle's Bad Juju actually does affect both values. I updated the talent to clarify instead.

Ember Spirit Fire Remnant alt-text is referring to how many charges it *starts* with, so it isn't redundant with "max charges" in the base tooltip.

Hoodwink Decoy says Dispellable because the invisibility on Hoodwink is dispellable, even if the illusion effect isn't. This is one of many cases where an ability has parts that can be dispelled and parts that can't. I have an idea for how to clarify this, but it will take some time before it can ship as a general solution for all heroes.

**Comment by chickenwyr** [comment]
> Damage Type text isn't colored if the damage type can vary or is unknown. It's often unknown if the ability applies bonus damage, although it's true that bonus damage is typically applied to attacks as physical damage. A good example of the former is Elder Titan's Echo Stomp isn't red because the Spirit Form uses the same ability but deals magical damage instead.


^ is this bullet point in reference to spells like Metamorphosis, Refraction, etc? If so, what do you mean by "unknown"? I mainly bring up the fact most "bonus attack damage" spells lack a damage type descriptor/colour because some spells (like Refraction, Searing Arrows) DO show red physical damage values, and I reckon consistency is useful.

**Comment by nathank-valve** [comment]
Yes, it is. Basically those abilities give "bonus attack damage" in code, but there's no damage type associated with it - just whatever type of damage a hero's attack deals. Technically speaking, if a hero was introduced that dealt magic damage with their base attack, Invoker's Alacrity (for example) would give them bonus magic damage while still giving everyone else bonus physical damage. Obviously there aren't any heroes like that, so I do intend to go through these and override them to display as physical damage text coloring. I left those items unchecked until I can get to that.

**Comment by moverperfect** [comment]
You have ticked " Glaives of Wisdom tooltip incorrectly says permanent Intelligence is stolen if the target has the Glaives of Wisdom debuff when it dies - this is not the case." for Silencer but for me this is still an issue with the tooltip.

**Comment by nathank-valve** [comment]
Just tested in demo mode - the tooltip is correct, which is why I crossed it out. Silencer will steal a permanent 2 Intelligence if any enemy has the Glaives debuff and is killed within 925 range of Silencer. If you have a specific repro case or match ID where this did not happen, let me know.

**Comment by chickenwyr** [comment]
> Just tested in demo mode - the tooltip is correct, which is why I crossed it out. Silencer will steal a permanent 2 Intelligence if an enemy has the Glaives debuff and is killed within 925 range of Silencer. If you have a specific repro case or match ID where this did not happen, let me know.

I think the issue here is that the Glaives debuff is not needed to get the Int steal - he can just exist in the range and steal int, no debuff required.

**Comment by moverperfect** [comment]
> > Just tested in demo mode - the tooltip is correct, which is why I crossed it out. Silencer will steal a permanent 2 Intelligence if an enemy has the Glaives debuff and is killed within 925 range of Silencer. If you have a specific repro case or match ID where this did not happen, let me know.
> 
> I think the issue here is that the Glaives debuff is not needed to get the Int steal - he can just exist in the range and steal int, no debuff required.

Exactly this, if you check the 7.25 changelog for silencer here https://dota2.fandom.com/wiki/Silencer/Changelogs it describes the cases where INT steal happens and it is not a requirement for the Glaives debuff to be applied(tested in demo mode to be the case) and the changelog doesn't mention this changing since 7.25.

To confirm:
Tooltip says that the debuff needs to be applied for the INT steal to happen
Tested in Demo mode, Silencer just needs to stand in range of enemy hero dying to receive permanent INT steal

**Comment by nathank-valve** [comment]
You are correct, thanks! I had forgotten about that case. Tooltip will be updated to remove the word "affected" and I'll add a note to clarify as well.

**Comment by LokeLok** [comment]
> Feral Impulse shows no range indicator when hovered over. 

  It's global since 7.28.

> Waning Rift shows no range indicator when hovered over. 

It has range indicator now. 

> Reincarnation should show an AOE indicator when hovered over with scepter. 

Also when having aghs on Wraith King, it removes the range indicator for the slow.

**Comment by TheUnholyWrath** [comment]
- Lina's Flame Cloak buff tooltip does not show the Spell Amplification value, only the % sign
- Nether Swap damage reduction buff does not use the description part of its tooltip ("Damage received reduced by %dMODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE%%%.").
- Queen of Pain's level 15 talent shows -0.7s Shadow Strike Damage Interval, it should be -0.5s
- Leshrac's Nihilism ability and debuff tooltip say it does Increased Magic Damage but it actually reduces Magic Resistance
- Nyx Assassin's Shard ability says it does Magic Resistance Reduction but it actually does Increased Spell Damage (debuff tooltip says this correctly) #459
- Bane's Fiends Grip Aghanim Scepter illusion debuffs don't have a tooltip
- Sand King's Sand Storm does not use its buff tooltip ("Sand Storm" "Turns you invisible and applies %dMODIFIER_PROPERTY_TOOLTIP% damage every second to nearby units."). Instead it just says "Invisible" " "
- Sand King's Caustic Finale does not use the debuff for the slow ("Caustic Finale Slow" "Movement speed slowed by %dMODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE%%%.")
- Drow Ranger's Gust debuff says "Miss chance increased by 0%." The talent for miss chance was removed in 7.32.
- Morphling's Aghanim Scepter steals 20% of all stats but the buff tooltip only mentions the 20% of the attribute of the enemy that was morphed into
