### ISSUE TITLE
[Major BUG] Using <space> as ALT Cast takes camera to mid lane T1 tower

### ISSUE THREAD

**Issue by centisiah** [ValveSoftware/Dota2-Gameplay#25750]
Played ursa. My ALT cast is binded to space key. First key down takes me to T1 tower mid lane and back to hero. Unable to use any ALT cast functions in the whole game. Game breaking. Ranked resulted in lost.

**Comment by centisiah** [comment]
issue also replicated in custom lobby

**Comment by centisiah** [comment]
did not change my settings from previous patch. even after trying to adjust hotkeys to find a solution - unable

**Comment by SahilValve** [comment]
Hi can you send me a picture of your settings?

**Comment by centisiah** [comment]
![Image](https://github.com/user-attachments/assets/12124694-4be5-4b2c-b22e-28bac3d32c3e)
![Image](https://github.com/user-attachments/assets/7ffe084e-8bcc-4373-ab58-936b08020ffa)
![Image](https://github.com/user-attachments/assets/1d44d4ea-9da9-4db6-a5e3-d5c1fdb285fe)
![Image](https://github.com/user-attachments/assets/92754724-6c89-4f3b-b136-58474f0c0363)

**Comment by centisiah** [comment]
![Image](https://github.com/user-attachments/assets/6ab024c2-6db7-44b6-8297-fde34366de91)

**Comment by centisiah** [comment]
the ALT cast goes into a weird 'saved camera position' which appears to be mid lane T1 tower. Never had this issue before in my life.

**Comment by SahilValve** [comment]
This is very strange. All of your camera positions are not bound I'm assuming? Was Space working like a alt-modifier at all?

**Comment by SahilValve** [comment]
Do you mind if you try resetting your hotkeys fully and seeing if that fixes the problem?

**Comment by centisiah** [comment]
i have already done that to no avail. another player in my lobby also had a similar issue

**Comment by centisiah** [comment]
all ALT cast functions are unusable. like ALT + right click on items for range for e.g

**Comment by SahilValve** [comment]
If you unbind Space from Alt-modifier does that fix it?

**Comment by centisiah** [comment]
when i do it, my space bar still brings me back to the saved camera position on mid lane

**Comment by SahilValve** [comment]
Can you try rebinding "Show Recent Event" to some other random key and seeing if that fixes it?

**Comment by centisiah** [comment]
i tried it as suggested. now BOTH keys take me to mid T1 tower.

**Comment by centisiah** [comment]
previously show recent event was unbinded. seems like its a Show Recent Event bug thats tied to my space key which I use every match

**Comment by SahilValve** [comment]
So when you did this - this kept "Show Recent Event" as unbounded?

<img width="1242" alt="Image" src="https://github.com/user-attachments/assets/cb7a2fdb-5b18-4546-9a8e-b6e91d1c0155" />

**Comment by SahilValve** [comment]
I can reproduce the bug. Am looking into it now. Thanks for all of the information

**Comment by centisiah** [comment]
thank you. Another bug that i have is for the hero Ursa with aghanim. It allows him to cast Enrage while disabled. However, his status resistance is no longer applied when he does that. For e.g, when Huskar ulti's Ursa 1) If Ursa casts Enrage after his ulti progs, the status resistance is not applied (full duration Huskar Ulti)   2) if Ursa cast enrage before huskar ultis, status resistance is applied resulting in lower duration of huskar's ulti. 

This is game breaking because buying aghanim scepter on Ursa is essentially no longer useful if this is not fixed. Status resistance should be applied during enrage consistently through its full duration. Thank you

**Comment by centisiah** [comment]
because of scenario 2), it defeats the entire purpose of buying aghanim scepter 4k gold on Ursa

**Comment by centisiah** [comment]
should I open a separate Bug page for this or are you able to check-in on this issue?

**Comment by centisiah** [comment]
huskar with aghanim scepter taunt effect, to be specific

**Comment by SahilValve** [comment]
Yes feel free to make another issue with that bug

**Comment by centisiah** [comment]
you seem reliable. will this post be sufficient to work on it?

**Comment by centisiah** [comment]
i noticed this bug as well during the recent blast 3 and dream league

**Comment by centisiah** [comment]
just to update, it hasnt been resolved

**Comment by SahilValve** [comment]
We've just shipped a client update that should fix this. Thanks for the report.

**Comment by centisiah** [comment]
thanks for the work Sahil. timely and reliable.

**Comment by Nomore1992** [comment]
I have a new, probably connected, issue. Space bar now always focuses the hero. I cannot find any setting to turn this off. But this makes using space as alt modifier impossible. 

For example: I have set "alt+f" to my inventory slot for wards and use the option "follwo hero during "select hero"". When i press "space + f" my screen jumps to my hero and the ward is not placed where i wanted to. 
Also shop is "space+s" but it now opens and closes at the same time.

I asked a friend and he has the same connection of space to focus his hero.

However, i have a second steam account on my computer where the behavior is correct. I reset my settings on the first accound and rebuild them from screenshots of the second, but still similar behavior. How is this possible?
Additionally. If i reset my settings, space is connected to "screen to last event". That works but if delete this connection, somehow "space selects hero" is turned on, without being set anywhere.

**Comment by SahilValve** [comment]
Hi, we are going to be shipping another fix. If you run the command `unbind "SPACE"` in console this should fix it.

**Comment by Nomore1992** [comment]
Thanks so much! Seems to work.

**Comment by centisiah** [comment]
Sahil, this space bar to mid lane BUG came back again

**Comment by SahilValve** [comment]
Enter `unbind "SPACE"` into your console. We're shipping a fix soon.

**Comment by centisiah** [comment]
Thank you sahil. Quickcast is still not working for neutral item and TP scroll

**Comment by centisiah** [comment]
Sahil, this midlane bug thing with SPACE key is back. Previously the unbind in console command works. but its not working now. even after i restarted dota multiple times

**Comment by SahilValve** [comment]
Hi @centisiah can you follow these steps:

* Could you all access this url: https://store.steampowered.com/account/remotestorageapp/?appid=570
* Download the file user_keys.vcfg
* And upload it here.

Additionally for your quickcast not working for neutral item and TP scroll. Could you send a picture of your settings under Abilities & Items

**Comment by SahilValve** [comment]
Hi @centisiah - we've just shipped another update that should address this. Let me know if it doesn't.

**Comment by centisiah** [comment]
Hey Sahil, can you please fix the QUICKCAST neutral item and QUICKCAST TP scroll. Its only CAST, i need QUICKCAST. Its affecting my gameplay

![Image](https://github.com/user-attachments/assets/8dde0401-ef25-4495-afee-a99f88af3765)

**Comment by SahilValve** [comment]
Hi @centisiah - another update has gone out to fix the Quickcast issue. Let me know if there are any other issues you run into.

**Comment by centisiah** [comment]
thanks Sahil fixed. Can you please look into stricter behavior score and match quality/algorithm of games since patch. Ever since patch release, there are extremely alot of griefers from 5.2k-5.6k bracket. i lost 400 MMR over the week which is extremely strange. theres always something extremely odd with my teammate in each game. Games are not even close. played since 2012. SEA bracket.  not a complaint. thanks
