### ISSUE TITLE
Shadow Fiend Arcana Visual Bug

### ISSUE THREAD

**Issue by FangedLion** [ValveSoftware/Dota2-Gameplay#26088]
### Cosmetic Item Name

Demon Eater

### Description

shadow fiend's arcana's fire visuals are misplaced and appear in front of his face instead of at the top of his head.

### Example Match ID

8310784393

### Screenshots

![Image](https://github.com/user-attachments/assets/cb13a3c0-ab11-4ef6-9a02-6577ab78515e)

![Image](https://github.com/user-attachments/assets/acd4f906-635f-4fc4-b6d9-140b252a1331)

**Comment by golovachmode** [comment]
i have this bug too

**Comment by jeffhill** [comment]
This is fixed in the build we just shipped. Thank you for the bug report!

**Comment by WaynettON** [comment]
how to fix it?

**Comment by FangedLion** [comment]
Hi, this bug is not fixed in the current build if you're referring to the most recent steam update. Could this issue please be reopened?

![Image](https://github.com/user-attachments/assets/9e100adf-3e73-4906-b01a-0b0d56e169db)

**Comment by Astiberon** [comment]
> This is fixed in the build we just shipped. Thank you for the bug report!

Hello Jeff, This bug is still not fixed.

![Image](https://github.com/user-attachments/assets/0b7b70ed-e37a-448a-99c7-9147ce74a697)

**Comment by bizzozeron** [comment]
Fixed in future update.

**Comment by FangedLion** [comment]
> Fixed in future update.

Don't be so confident haha.

**Comment by Astiberon** [comment]
FIXED
![Image](https://github.com/user-attachments/assets/5f3c1728-30ad-4e65-b14d-d62c42fa685f)
