### ISSUE TITLE
LABS: Hotkeys option has completely broken invoker's hotkeys

### ISSUE THREAD

**Issue by zeeshanbukhari** [ValveSoftware/Dota2-Gameplay#26244]
### Description

For context I play invoker on non-legacy keys (QWE DF R), but play other heroes on legacy keys. 

Current behavior: I only see legacy keys in in-game spells for invoker despite the "use legacy key" checkbox disabled. I can cast my spells using both D and F, and the shown legacy hotkey. So both are being used.

**I strongly suspect this is because I've used the labs hotkey option "Set unit hotkeys to legacy keys", because I didn't encounter it before I clicked this.** It's possible that the new update caused it, but I've tested it on my brother's account, who plays with the same settings for invoker as I, and it's fine there.

Please fix this because my hero is literally (literally) unplayable because of this :(. I've attached a match ID as an example, but it's clearly happening on hero demo as well, pics attached.

PS. Some other issues I encountered: as magnus, I could not set item hotkey to "F" - every time I clicked F the sound on-click dota sound would play, meaning it was assigned somewhere else internally. Exact same thing with qop using "Q" item hotkey. These are the only ones I've encountered so far.

### Example Match ID (and possibly Timestamp)

8317442573

### Screenshots

![Image](https://github.com/user-attachments/assets/0b8d1d2a-ef78-407f-a9f5-68ce95be62a2)

![Image](https://github.com/user-attachments/assets/f0a8185b-483b-4471-844c-cc5438a2922c)

![Image](https://github.com/user-attachments/assets/5dc4bb3e-4630-407e-852c-7ff01ef059ee)

**Comment by roycecarr12** [comment]
hi have you found a solution to this issue? i accidentally pressed the LABS legacy hotkey button as well and it messed up my invoker hotkeys.

**Comment by zeeshanbukhari** [comment]
Sadly nope. still can't play invoker. F for both of us :(

**Comment by zeeshanbukhari** [comment]
@roycecarr12 Hey man, someone on reddit posted a fix for it so sharing here

Enable console and use this command:
dota_custom_invoker_spell_keys false

It should fix it. Though you might have to use it every time you start dota.

**Comment by gisketch** [comment]
> [@roycecarr12](https://github.com/roycecarr12) Hey man, someone on reddit posted a fix for it so sharing here
> 
> Enable console and use this command: dota_custom_invoker_spell_keys false
> 
> It should fix it. Though you might have to use it every time you start dota.

hi this didnt work for me but the thing is i did this fix while in game, does it only work before starting a game?

**Comment by zeeshanbukhari** [comment]
Yeah try using it in the main menu before you start a game/demo

**Comment by morphtek** [comment]
damn i was losing my mind it is so bugged it shows different hotkey for each invoked spell then when you turn on legacy it still shows it but it works properly with D and F but only until 2 spells that are using D and F then it stop working how could you let this through its january 2025 and it still bugged in game

**Comment by carmelopaz0708** [comment]
To fix this issue, you need to edit the `user_convars.vcfg` file found in your user settings.

First, disable steam cloud sync if you have it. Then navigate to the steam user settings. In Windows, it should be in Documents. In Linux, its probably in your `home/.steam` path.

Open `user_convars.vcfg` with a text editor. Then add this text in a new line anywhere in the file.

`"dota_custom_invoker_spell_keys" "false"`

Save this file then exit. Open Dota and check Invoker. Your UI should go back to whatever it was before. You can finally turn on steam cloud to sync your changes.

I had this exact issue happen to me. The `dotakeys_personal.lst` file I was messing with didn't want to go back to QWEDFR even after a full reset. I'm guessing the cloud sync settings kept overriding the hotkeys, or the legacy option was saved somewhere in user space. Either way, if you do the steps above, this should solve your issue.
