### ISSUE TITLE
YUNO 2025 sticker displaying picture as PSG.LGD 2022 player

### ISSUE THREAD

**Issue by zxcjf10** [ValveSoftware/Dota2-Gameplay#27391]
### Description

i purchased the Yuno 2025 sticker and when i open it, i receive a 2022 sticker with name Yuno but a picture of a PSG.LGD player

steam id : 163678209

### Screenshots

<img width="547" height="1010" alt="Image" src="https://github.com/user-attachments/assets/92b1c94a-03db-4b45-a637-a339caa298c5" />

<img width="1652" height="1024" alt="Image" src="https://github.com/user-attachments/assets/f74f23fe-abfb-4561-9037-53eb47387429" />

https://github.com/user-attachments/assets/bbc0aa76-be84-4237-aab7-a31a2d1c444c

**Comment by eugene-valve** [comment]
Hi, I believe this should be fixed after our update last night. Please let me know if your item still has an issue.

**Comment by zxcjf10** [comment]
Still the same sir.

[image: image.png]

**Comment by eugene-valve** [comment]
Hi, could you try checking now?

**Comment by zxcjf10** [comment]
still the same sir , here's another screenshot with timestamp
[image: image.png]
[image: image.png][image: image.png]

**Comment by zxcjf10** [comment]
i already restarted my dota2 before checking again btw

**Comment by eugene-valve** [comment]
Thanks for letting me know, that helps rule some things out. We're working on a fix now.

**Comment by eugene-valve** [comment]
Hi, are you continuing to have issues? We made some changes on Friday evening that should have fixed this problem.

**Comment by tofffee** [comment]
> Hi, are you continuing to have issues? We made some changes on Friday evening that should have fixed this problem.

Are you planning to add new functionality to stickers? stick them on characters, objects, etc.
