### ISSUE TITLE
Camera Bug - Select Hero is NOT Centering the Camera

### ISSUE THREAD

**Issue by Willy-the-bug-reporter** [ValveSoftware/Dota2-Gameplay#28690]
### Description of the bug:

**(With the 'Hold to Select Hero' setting enabled) When trying to center the camera with 'Select Hero' after adjusting the camera with Camera Grip, the camera will not be centered.**

Instead, the camera angle created will be offset to wherever you adjusted the camera to with Camera Grip. Pressing 'Select Hero' will also briefly overlay two different camera positions at once, creating a very disorientating effect.

### Videos showcasing the bug:

- https://packaged-media.redd.it/q5nm0ql3uanf1/pb/m2-res_1080p.mp4?m=DASHPlaylist.mpd&v=1&e=1759561200&s=7dfc4f192de9c1088f6ba455e9049302e895df7b

- https://www.youtube.com/watch?v=u64uakUVO0w

### Steps to reproduce this bug:
 
1. Enable 'Hold to Select Hero'

1. Press 'Select Hero' to center the camera on your hero. Hold the key down. 
(This "locks" the camera centered on your hero if the option 'Hold to Select Hero' is enabled)

2. Adjust the camera using Camera Grip 
(while the camera is locked in the centered position)

3. Let go of the 'Select Hero' key 
(this will "unlock" the camera)

4. Press the 'Select Hero' key 
(this will showcase the bug, the camera will NOT be centered)

5. You can:

- Hold the 'Select Hero' key to see how the camera is locked at an offset angle.
- Spam the 'Select Hero' key to easily see how there are two camera angles being briefly overlayed on top of each other.

### Cancelling the bug:

This bug can be cancelled by making any re-adjustment of your camera with Camera Grip, if you do so while NOT holding down Select Hero (i.e. while the camera is free to move).

Being able to cancel the bug **does not make the issue any less frustrating**, as it will constantly reoccur if you play with Camera Grip and center your camera a lot.

### Personal thoughts:

This bug heavily affects my gameplay - **it occurs very easily and very often.** 

You expect the camera to move to directly over your hero, but instead it could be way off somewhere else. An entire team fight might move offscreen when you do this.

It makes the camera act in an unexpected way, forcing me to make  readjustments - which are especially costly during fights.  As a result, I am forced to not use Select Hero much. 

I would love if Valve could try and fix this issue because it's an extremely fun and intuitive way to use the camera with Camera Grip and centering the camera!

### Extra Notes:

Adjusting the camera in this way with Edge Panning or with keybinds (e.g. WASD) does not cause this bug. 
It only occurs with Camera Grip - clearly an unintended interaction.

**Comment by beep317** [comment]
which hotkey do you use to drag camera grip? i didn't have this problem when i try to do ur bug

**Comment by Willy-the-bug-reporter** [comment]
@beep317 I use the default, middle mouse button. Are you sure you're doing it correctly? 

**Remember to enable 'Hold to Select Hero' in the settings!** 

For me, Select Hero is spacebar. So for me to recreate it: 
Hold spacebar -> camera drag with middle mouse button -> let go of spacebar -> press spacebar and the camera won't be centered.

**Comment by beep317** [comment]
Yes, same problem

**Comment by VetaLioSTV** [comment]
Yeah, i had this for while ago... its like camera not centered properly in some cases, instead it shifted in different positions (usually vertically down / lower ). Dont remember when this bug appeared(i guess from 2024, possible even 2023), but its supper annoying... You to make extra movement / action to reset that camera shift and your selected hero will be positioned again in center.

**Comment by Willy-the-bug-reporter** [comment]
Praying this gets addressed in 7.40 🙏🙏🙏 Keep cooking Valve

**Comment by VetaLioSTV** [comment]
> Praying this gets addressed in 7.40 🙏🙏🙏 Keep cooking Valve

i dont think honestly... I have that problem on different scenario and its super annyoing, like something wrong with focus when you open store / choose monster hunter enemy and etc.

I will try to make notes and i will come back here with video example. This is super old bug and still reproducible :(
