### ISSUE TITLE
[Pinned Items] In Shop, players are able to somehow lose pinned item slots over time. I personally have three left. There is no way to restore the slots that are lost, therefore some of us are unable to pin 6 items anymore.

### ISSUE THREAD

**Issue by clovertheswift** [ValveSoftware/Dota2-Gameplay#3225]
### Description

[Pinned Items] In Shop, players are able to somehow lose pinned item slots over time. I personally have three left. There is no way to restore the slots that are lost, therefore some of us are unable to pinned 6 items anymore.

### There's an issue with pinned items.
Throughout using the pinned items system in dota, I've noticed that I started to lose some of my slots. When I compare to other players, they still have six, maybe five slots, but I only have three left. I couldn't find a way to reset pinned items.

I don't know how to replicate this problem, since I haven't noticed when it happened, but rather after it already had. My best guess, however, would be using the pinned items system in limited-time gamemodes (with limited-time items) such as Siltbreaker, Aghanim's Labyrinth etc. - in fact, I could say that if I am to pin down when this issue occurred, it was some time after Aghanim's Labyrinth concluded. Could be related... could not be.

### **What I would propose:**
**a) super straightforward solution:** Just add a button that refreshes pinned items and resets them to "factory settings". If there was an issue like this, or some other inconceivable issue, the player could easily hit the reset button and continue using pinned items.

**b) overhaul solution (ps: I'm just taking guesses at how it works, I'm no coder myself- sorry.):**
Make pinned items function more like quickbuy: tossing items in there that remain in there, instead of having a predefined number of slots that are "replaced" by dragging items on it. This way, you would solve another problem: maybe I just want two items pinned. I won't have four empty _(you can't even have them empty, they will have the last thing you put in there, fullstop)_ slots that are just sticking out like a sore thumb. Or maybe I want to have 12 items pinned- which is double the original amount we are able to have.  Basically, this way, we could have more flexibility in pinned items.

### Screenshots

https://imgur.com/a/MMgWDbk
![hadfad](https://user-images.githubusercontent.com/113874182/190948515-fa778115-3090-40ab-91d5-4d624db41d4e.PNG)

**Comment by Avarise831** [comment]
https://youtu.be/nsmLazRA1Lw - it might be help you before valve fix that

**Comment by clovertheswift** [comment]
> https://youtu.be/nsmLazRA1Lw - it might be help you before valve fix that

Hey, unfortunately this isn't working for me, **but this is still a greatly helpful contribution. It confirms that the pin slots are disappearing because of invalid items not recognised by default dota**, which is why I started to lose slots after using the pin system for Aghanim's Labyrinth etc.

In the video, the person fixes their problem by replicating the bug enough times to where it breaks and resets itself, but it seems like the trigger for the bug is fixed. That means I can't trigger the bug again to the point where it'll reset for me, and since there is no official way to reset the pinned items, it's pretty much stuck that way.

**Comment by Frost90** [comment]
> 

The solution from the video didn't work for me either, currently stuck with only 2 pinned items instead of 6

**Comment by Avarise831** [comment]
> > 
> 
> The solution from the video didn't work for me either, currently stuck with only 2 pinned items instead of 6

I think you need to create a post on reddit with this issue with a link to this github for promotion idk

**Comment by somewherebutnothere** [comment]
This issue still persists. I do not knwo exactly when I lost the slots but I have only 2 available.

**Comment by Avarise831** [comment]
#1286
