### ISSUE TITLE
PLAY VS BOTS CO-OP issue

### ISSUE THREAD

**Issue by Innocence** [ValveSoftware/Dota2-Gameplay#8968]
### Description

If you disconnect in a CO-OP PLAY VS BOTS game you can't do anything to your hero after reconnect.

![QQ截图20230515191710](https://github.com/ValveSoftware/Dota2-Gameplay/assets/1294867/878806c1-06af-4bd1-aa53-d2389718a06a)

### Screenshots
![QQ截图20230515191911](https://github.com/ValveSoftware/Dota2-Gameplay/assets/1294867/57d21256-9269-42a7-a8b7-14d8fdc44b3d)

**Comment by DanyNourallah** [comment]
yup should be fixed soon, pretty frustrating specially half way through the Match!

**Comment by 346896312** [comment]
fix fix come on! ValveSoftware

**Comment by rlabrecque** [comment]
Still happens as of today

**Comment by Brighd** [comment]
Maybe there's a way to escalate this issue? The bug is still there
