### ISSUE TITLE
[CRUSHING SERVER] Earth Spirit with Refresher Orb

### ISSUE THREAD

**Issue by AleksandrKuznetsov2** [ValveSoftware/Dota2-Gameplay#9086]
### Ability name

Magnetize, Stone Remenant

### Description

Earth Spirit can crush servers with using Magnetize in creeps with 18 Stone Remenants after he used refresher orb.

**HOW REPRODUCE**
1. Create Custom Lobby DotA common map with enabled cheats(simplify for reproduce). 
2. Pick Earth Spirit.
3. Execute cheats: -lvlup 9, -item refresh. 
4. Learn ultimate Magnetize.
5. Wait when middle creeps are meets beyond t1 towers. 
6. Use 9 Stone Remenant, use refresher, use 9 Stone Remenant again, use Magnetize. 
7. Wait when magnetize effect end and remenants are dissapear.
8. Dota 2 Client close without winerrors. Server are crushed. 

### Example Match ID (and possibly Timestamp)

7145158484

**Comment by AleksandrKuznetsov2** [comment]
> 
So, it means bug fixing needs only on client, if i understand you correctly. 
Anyway, bug still reproducing in any type of games 🤡🤡🤡

**Comment by Jimmy9877** [comment]
This also happend to me in a ranked game, the ES crashed the game on purpose:
https://github.com/ValveSoftware/Dota2-Gameplay/issues/9330

**Comment by crusty5g** [comment]
we were winnig this ranked game
match id: 7146231495
earth spirit at
48:40 selling his items and buy refresher orb then at
49:10 he rapidly uses all stone remenant and magnetize to make game crash
and game turnes to safe to leave and he saves his mmr and we don't get our mmr

**Comment by Aluerie** [comment]
fixed, pls close

**Comment by Jimmy9877** [comment]
Some collaborator said that this issue should be fixed in the next upcoming update, however I have no clue if the source is trustworthy.

**Comment by Jimmy9877** [comment]
It's been fixed among alot of other bugs thanks boys :)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/91598432/d66fc282-78cd-400b-952e-2ab339decbe1)

**Comment by webberjiang** [comment]
Bug seems not fix, played a recent match, earth spirit still able to crush the game
Match ID: 7180139236

**Comment by kirsoms** [comment]
bug is still in the game. Even the replay crashes.
Match ID: 7180947190  38:30

**Comment by taylortapio** [comment]
Hello world. This bug is not fixed. 7211246829. Pls refund +25 mmr too plsthx

**Comment by AleksandrKuznetsov2** [comment]
still reproducing

**Comment by KAMOwO** [comment]
Just happened to me as well. Match ID: 7212776933

**Comment by AleksandrKuznetsov2** [comment]
🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡

**Comment by eric1294** [comment]
Happened to me just a few minutes ago. I thought my graphics card went out or something. Match ID: 7231932478

**Comment by SaltyManGit** [comment]
this bug still exists. earth spirit abused this against me.
game id 7233494825.

**Comment by halaydzhak** [comment]
This bug still exists. Example is 7256446188. Earth Spirit using refresher to create tons of remnants and crush the server

**Comment by zzaiens** [comment]
Bug still exists. 7257917844

**Comment by trantus** [comment]
Bag still exists

**Comment by DenchikSprite** [comment]
Bug still exists. 7260890387

**Comment by sonicfon** [comment]
FIX YOUR DAMN GAME VALVE, OR MAKE EARTH SPIRIT UNPICKABLE IN RANKED, TILL YOU FIX IT. YOU DONE IT MANY TIMES, C'MON!

**Comment by Ageoshka** [comment]
opened this issue on May 9
07.31.2023 STILL WORKING 
match 7264045331 42m 45s
VALVE BUG IS STILL WORKING BY 3 month

**Comment by jeffhill** [comment]
A second, and hopefully final, fix for this will ship with the update today. Thanks for all the reports!

**Comment by Atari2** [comment]
> A second, and hopefully final, fix for this will ship with the update today. Thanks for all the reports!
I still managed to reproduce it in a local lobby, doesn't happen every time but placing all 13 remnants, then refreshing, then placing another 13 remnants (all near creeps), then ulting and then waiting for the remnants to break crashed the game
